name: CI

on:
  pull_request_target:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]
        pnpm-version: [7.18.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set pnpm version
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
        env:
          FORCE_COLOR: 0
      - name: Install dependencies
        run: pnpm install
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: echo "ENV=production" >> $GITHUB_ENV
      - name: Run lint
        run: pnpm run lint-staged

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]
        pnpm-version: [7.18.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set pnpm version
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
        env:
          FORCE_COLOR: 0
      - name: Install dependencies
        run: pnpm install
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: echo "ENV=production" >> $GITHUB_ENV
      - name: Run unit tests
        run: pnpm run test:unit
